server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: clientes-service
              uri: lb://CLIENTES-SERVICE
              predicates:
                - Path=/api/v1/clientes/**,/api/v1/direcciones/**
              filters:
                - AddResponseHeader=X-Gateway, API-GATEWAY
            - id: vehiculos-service
              uri: lb://VEHICULOS-SERVICE
              predicates:
                - Path=/api/v1/vehiculos/**,/api/v1/categorias/**
              filters:
                - AddResponseHeader=X-Gateway, API-GATEWAY
            - id: reservas-service
              uri: lb://RESERVAS-SERVICE
              predicates:
                - Path=/api/v1/reservas/**,/api/v1/estados-reserva/**
              filters:
                - AddResponseHeader=X-Gateway, API-GATEWAY
            - id: pagos-service
              uri: lb://PAGOS-SERVICE
              predicates:
                - Path=/api/v1/pagos/**
              filters:
                - AddResponseHeader=X-Gateway, API-GATEWAY
            - id: sucursales-service
              uri: lb://SUCURSALES-SERVICE
              predicates:
                - Path=/api/v1/sucursales/**,/api/v1/regiones/**
              filters:
                - AddResponseHeader=X-Gateway, API-GATEWAY
            - id: empleados-service
              uri: lb://EMPLEADOS-SERVICE
              predicates:
                - Path=/api/v1/empleados/**
              filters:
                - AddResponseHeader=X-Gateway, API-GATEWAY
            - id: reportes-service
              uri: lb://REPORTES-SERVICE
              predicates:
                - Path=/api/v1/reportes/**
              filters:
                - AddResponseHeader=X-Gateway, API-GATEWAY
          httpclient:
            connect-timeout: 3000
            response-timeout: 5s

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
