spring.application.name=mssucursales
server.port=8085

spring.datasource.url=jdbc:mysql://localhost:3306/prueba1?createDatabaseIfNotExist=true&serverTimezone=America/Santiago
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false



logging.level.com.duoc.mssucursales=INFO
clientes.url=${CLIENTES_URL:http://localhost:8081}
vehiculos.url=${VEHICULOS_URL:http://localhost:8082}
reservas.url=${RESERVAS_URL:http://localhost:8083}
pagos.url=${PAGOS_URL:http://localhost:8084}
